meta_product_name: "Duno"
meta_title: "Duno - How you learn is everything"
meta_description: "Duno is an easy way for you and your company to share knowledge through an e‑learning track. There’s no app or software download required. Just choose your own personalized URL, your content to share and create your track using your internet browser with just few clicks."
meta_image: "scholar.png" # should exist in `app/assets/images/`
